-- T_MATRICULA

CREATE TABLE T_MATRICULA(
	Matricula VARCHAR(7) PRIMARY KEY NOT NULL,
	Modelo VARCHAR(45) NOT NULL,
	Fabricante VARCHAR(45) NOT NULL
);

-- T_AVION

CREATE TABLE T_AVION(
	Matricula VARCHAR(7) PRIMARY KEY NOT NULL,
	Autonomía TINYINT NOT NULL,
	Numero_pasajeros INT NOT NULL,
	CONSTRAINT FK_Matricula_T_MATRICULA_AVION
	  FOREIGN KEY (Matricula) REFERENCES T_MATRICULA(Matricula)
);

-- T_PUESTO

CREATE TABLE T_PUESTO(
	Codigo_puesto INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Nombre VARCHAR(45) NOT NULL
);

-- T_TRABAJADOR

CREATE TABLE T_TRABAJADOR(
	ID_Trabajador INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Nombre VARCHAR(45) NOT NULL,
	Apellido_1 VARCHAR(45) NOT NULL,
	Apellido_2 VARCHAR(45),
	Categoria_profesional VARCHAR(127) NOT NULL,
	Codigo_puesto INT NOT NULL,
	CONSTRAINT FK_Codigo_puesto_T_PUESTO_TRABAJADOR
	  FOREIGN KEY (Codigo_puesto) REFERENCES T_PUESTO(Codigo_puesto)
);

-- T_TELEFONOTRABAJADOR

CREATE TABLE T_TELEFONOTRABAJADOR(
	ID_Trabajador INT NOT NULL,
	Telefono VARCHAR(31) NOT NULL,
	PRIMARY KEY (ID_Trabajador, Telefono),
	CONSTRAINT FK_ID_Trabajador_T_TRABAJADOR
	  FOREIGN KEY (ID_Trabajador) REFERENCES T_TRABAJADOR (ID_Trabajador)
);

-- T_VUELO

CREATE TABLE T_VUELO(
	ID_Vuelo INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Fecha DATE NOT NULL,
	Aeropuerto_origen VARCHAR(127) NOT NULL,
	Aeropuerto_destino VARCHAR(127) NOT NULL,
	Matricula VARCHAR(7) NOT NULL,
	ID_Trabajador INT NOT NULL,
	CONSTRAINT FK_Matricula_T_AVION_VUELO
	  FOREIGN KEY (Matricula) REFERENCES T_AVION (Matricula),
	CONSTRAINT FK_ID_Trabajador_T_TRABAJADOR_VUELO
	  FOREIGN KEY (ID_Trabajador) REFERENCES T_TRABAJADOR (ID_Trabajador)
);

-- T_PASAJERO

CREATE TABLE T_PASAJERO(
	DNI_Pasajero CHAR(9) PRIMARY KEY NOT NULL,
	Nombre VARCHAR(45) NOT NULL,
	Apellidos VARCHAR(127) NOT NULL,
	Email VARCHAR(127) NOT NULL,
	Clase VARCHAR(2) NOT NULL,
	Asiento VARCHAR(4) NOT NULL,
	Contacto VARCHAR(45) NOT NULL,
	ID_Vuelo INT NOT NULL,
	CONSTRAINT FK_ID_Vuelo_T_VUELO
	  FOREIGN KEY (ID_Vuelo) REFERENCES T_VUELO (ID_Vuelo)
);

-- T_TELEFONOPASAJERO

CREATE TABLE T_TELEFONOPASAJERO(
	DNI_Pasajero CHAR(9) NOT NULL,
	Telefono VARCHAR(31) NOT NULL,
	PRIMARY KEY (DNI_Pasajero, Telefono),
	CONSTRAINT FK_DNI_Pasajero_T_PASAJERO_TELEFONOPASAJERO
	  FOREIGN KEY (DNI_Pasajero) REFERENCES T_PASAJERO (DNI_Pasajero)
	
);